lib.dir=lib
contrib=${lib.dir}/ant-contrib-1.0b3.jar

src.dir=src/main
main.dir=${src.dir}/java
resources.dir=${src.dir}/resources

build.dir.gradle=build
idea.dir=.idea
gradle.cache.dir=.gradle
gradle.wrapper.dir=gradle

ant.dir=ant
build.dir=${ant.dir}/build
classes.dir=${build.dir}/classes
rev.dir=${ant.dir}/rev
ant.lib.dir=${ant.dir}/lib
hash.dir=${ant.dir}/hash
native2ascii.dir=${ant.dir}/native2ascii
history.dir=${ant.dir}/history

test.classes.dir=${build.dir}/test-classes
test.dir=src/test/java
test.report.dir=${ant.dir}/test-reports
report.dir=${ant.dir}/report

ant.resources=ant-resources
music.file=${ant.resources}/music.mp3
params.file=${ant.resources}/parameters.properties
doc.dir=${ant.dir}/javadoc

server.user=s466310
server.host=se.ifmo.ru
server.port=2222
server.path=/home/studs/s466310/OPI_LAB3
server.pwd=****

svn.url=file:///Users/maria/svn_repo/OPI_LAB3

env.java.home.1=/Users/maria/Library/Java/JavaVirtualMachines/ms-17.0.16/Contents/Home
env.java.args.1=-Xmx256m -Dfile.encoding=UTF-8

env.java.home.2=/Users/maria/Library/Java/JavaVirtualMachines/ms-21.0.9/Contents/Home
env.java.args.2=-Xmx512m -Dfile.encoding=UTF-8

alt.dir=${ant.dir}/alt
alt.src.dir=${alt.dir}/src
alt.build.dir=${alt.dir}/build
alt.classes.dir=${alt.build.dir}/classes

alt.token.class1.old=CoordValidation
alt.token.class1.new=CoordValidationAlt
alt.token.class2.old=CheckAreaShape
alt.token.class2.new=CheckAreaShapeAlt

version=1.0
main.class=org.wineeenottt.Main
jar.name=${ant.project.name}-${version}.jar




